version: '3.1'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
 
  client:
    build: ./client
    environment:
      - PORT=3000  

  server:
    build: ./server
    environment:
      - PORT=3400      


volumes:
  mongo-db: