version: '3.1'

services:
  nginx:
    build: 
      context: ./client 
      dockerfile: Dockerfile.nginx
      args:
        NODE_ENV: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro    

      
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email wael.22@live.fr --agree-tos --no-eff-email --staging -d walltribute.com -d www.walltribute.com 

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    volumes:
      - ./public/images:/app/public/images
    environment: 
      - MONGO_URI=mongodb://walltributedb:eWy^B&Pfkd*E@mongo:27017/?authSource=admin    
    command: yarn start:prod
    depends_on:
      - mongo  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=walltributedb
      - MONGO_INITDB_ROOT_PASSWORD=eWy^B&Pfkd*E
    volumes:
      - mongo-db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin-123
      ME_CONFIG_MONGODB_ADMINPASSWORD: eWy^B&Pfkd*E
      ME_CONFIG_MONGODB_URL: mongodb://walltributedb:eWy^B&Pfkd*E@mongo:27017/



volumes:
  mongo-db: