version: '3.1'

services:
  nginx:
    build: 
      context: ./client 
      dockerfile: Dockerfile.nginx
      args:
        NODE_ENV: production
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    volumes:
      - ./media:/app/public
    environment: 
      - MONGO_URI=mongodb://root:root@mongo:27017/?authSource=admin    
    command: yarn start
    depends_on:
      - mongo  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db



volumes:
  mongo-db: