version: '3.1'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client

  client:
    build:
      context: ./client
      args:
        NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules
#    ports:
#     - 3000:3000  
    command: npm start  
    depends_on:
      - server
      - mongo  

  server:
    build:
      context: ./server
      args:
        NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
    environment: 
      - MONGO_URI=mongodb://root:root@mongo:27017/?authSource=admin    
    command: yarn dev
    ports: 
      - 3400:3400
    depends_on:
      - mongo  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081     



volumes:
  mongo-db: