version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=walltributedb
      - MONGO_INITDB_ROOT_PASSWORD=eWy^B&Pfkd*E
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017  

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: walltributeexpress
      ME_CONFIG_MONGODB_ADMINPASSWORD: walltributeexpress123
      ME_CONFIG_MONGODB_URL: mongodb://walltributedb:eWy^B&Pfkd*E@mongo:27017/

volumes:
  mongo-db: